name: liquefaction
favicon: null
layout_spectrum: 0.817434
typography_spectrum: 0.617599
title: Liquefaction Removal
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A8C890'
    - '#002048'
    - '#709880'
    - '#38A890'
    - '#70D8A0'
  brandStrength: 0.5415067551295067
  lightness: 0.0981557714197896
  saturation: 0.23510183637097204
  rhythmicContrast: 0.00276233386460778
purpose:
  - name: null
    item: null
    url: null
